### PR TITLE
fix: use route path instead of route name for bufferRouteState

### PR DESCRIPTION
**Pull request by benjaminrobinet**
As the routerMap of the FlowProvider is using the path as key and not the name. The buffer when using crossfade was not working.

### CODE REVIEW

**Comment by benjaminrobinet** [comment]
Well, we just needed to use the pageComponent.__name instead I guess. So no more need to set any route path ? Or may I missed something.

**Comment by benjaminrobinet** [comment]
Well, a bit more complicated than that.
But the issue with using "hardcoded" path is that in Nuxt we often don't really know the path. Like using vue-i18n (/nuxt-i18n). Maybe we could just go through the matched components of the `to` route ?

**Comment by Nam-Hai** [comment]
Yeah I used route.name because it makes sense to every /route/[id].vue to be treated the same. 
Hardcoding name in registerPath was totally a bad idea I agree. Good thing you did this PR, there was also a typo in the README.md

**Comment by benjaminrobinet** [comment]
@Nam-Hai What I did won't work as soon as you have like /sub/[slug], as the component name will be "slug" but the route name will be "sub-slug", might need to do it an other way.

**Comment by Nam-Hai** [comment]
o no

**Comment by Nam-Hai** [comment]
I'll revert these change then

**Pull request merged**
